"""AI Rewrite Suggestions — the only feature in this codebase that calls an
external LLM (Anthropic Claude). Weak-bullet *detection* is a local heuristic
(no API call); the *rewrite* text itself is generated by Claude in one
batched request per resume.

Fails closed and cheaply: if ANTHROPIC_API_KEY isn't configured, we raise
before ever constructing a client or making a network call.
"""
import json
from datetime import datetime, timezone

import anthropic

from app.core.config import settings
from app.models.resume import Resume
from app.schemas.rewrite import BulletRewriteSuggestion, RewriteSuggestionsRead
from app.services.resume_parser import extract_bullet_lines
from app.services.text_signals import BUZZWORDS

WEAK_OPENERS = [
    "responsible for", "worked on", "helped with", "duties included",
    "in charge of", "tasked with", "involved in", "participated in",
]

MAX_BULLETS = 8


class RewriteServiceError(Exception):
    """Base error for the AI rewrite-suggestions service."""


class RewriteNotConfiguredError(RewriteServiceError):
    """Missing/invalid ANTHROPIC_API_KEY — surfaced to the API as a 503."""


class RewriteProviderError(RewriteServiceError):
    """Network/rate-limit/malformed-response failure — surfaced as a 502."""


def _has_digit(text: str) -> bool:
    return any(ch.isdigit() for ch in text)


def select_weak_bullets(raw_text: str, max_count: int = MAX_BULLETS) -> list[dict]:
    """Pure heuristic, no LLM call. A bullet is "weak" if it opens with a
    passive phrase, has no quantified result, is very short, or leans on
    generic buzzwords instead of specifics."""
    weak: list[dict] = []
    for bullet in extract_bullet_lines(raw_text):
        lower = bullet.lower()
        reasons: list[str] = []
        if any(lower.startswith(opener) for opener in WEAK_OPENERS):
            reasons.append("starts with a passive, low-impact opener")
        if not _has_digit(bullet):
            reasons.append("no quantified result or metric")
        if len(bullet.split()) < 6:
            reasons.append("too short to convey real impact")
        if len([b for b in BUZZWORDS if b in lower]) >= 2:
            reasons.append("relies on generic buzzwords rather than specifics")

        if reasons:
            weak.append({"original": bullet, "reasons": reasons})
        if len(weak) >= max_count:
            break
    return weak


def _build_prompt(weak_bullets: list[dict]) -> str:
    lines = [
        f'{i}. "{item["original"]}"\n   Weaknesses: {"; ".join(item["reasons"])}'
        for i, item in enumerate(weak_bullets, start=1)
    ]
    return (
        "You are helping a job candidate strengthen weak resume bullet points. "
        "For each numbered bullet below, write one improved version: a single, "
        "concise, action-verb-led, achievement-oriented sentence. Never invent "
        "facts, numbers, team sizes, or job titles that aren't implied by the "
        "original text. If no metric is present, suggest in the rationale what "
        "*type* of metric the candidate should add — do not invent a number in "
        "the rewrite itself. Return exactly one item per bullet, in the same order.\n\n"
        + "\n".join(lines)
    )


_OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "items": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "rewritten": {"type": "string"},
                    "rationale": {"type": "string"},
                },
                "required": ["rewritten", "rationale"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["items"],
    "additionalProperties": False,
}


def generate_rewrite_suggestions(resume: Resume) -> RewriteSuggestionsRead:
    weak_bullets = select_weak_bullets(resume.raw_text or "")
    if not weak_bullets:
        return RewriteSuggestionsRead(
            resume_id=resume.id,
            suggestions=[],
            model=settings.ANTHROPIC_MODEL,
            generated_at=datetime.now(timezone.utc),
        )

    if not settings.ANTHROPIC_API_KEY:
        raise RewriteNotConfiguredError(
            "AI rewrite suggestions require ANTHROPIC_API_KEY to be configured on the server."
        )

    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    try:
        response = client.messages.create(
            model=settings.ANTHROPIC_MODEL,
            max_tokens=settings.ANTHROPIC_MAX_OUTPUT_TOKENS,
            thinking={"type": "disabled"},
            output_config={"effort": "low", "format": {"type": "json_schema", "schema": _OUTPUT_SCHEMA}},
            messages=[{"role": "user", "content": _build_prompt(weak_bullets)}],
        )
    except anthropic.AuthenticationError as exc:
        raise RewriteNotConfiguredError(
            "The configured ANTHROPIC_API_KEY was rejected (invalid key)."
        ) from exc
    except anthropic.PermissionDeniedError as exc:
        raise RewriteNotConfiguredError(
            "The configured ANTHROPIC_API_KEY lacks permission for this model."
        ) from exc
    except anthropic.RateLimitError as exc:
        raise RewriteProviderError(
            "The AI rewrite service is rate-limited. Please try again shortly."
        ) from exc
    except anthropic.APIConnectionError as exc:
        raise RewriteProviderError("Could not reach the AI rewrite service. Please try again.") from exc
    except anthropic.APIStatusError as exc:
        raise RewriteProviderError(f"AI rewrite service error: {exc.message}") from exc

    text = next((block.text for block in response.content if block.type == "text"), None)
    if not text:
        raise RewriteProviderError("The AI rewrite service returned an empty response.")

    try:
        items = json.loads(text)["items"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        raise RewriteProviderError("The AI rewrite service returned a malformed response.") from exc

    if len(items) != len(weak_bullets):
        raise RewriteProviderError("The AI rewrite service returned an unexpected number of suggestions.")

    suggestions = [
        BulletRewriteSuggestion(
            original=weak_bullets[i]["original"],
            rewritten=items[i]["rewritten"],
            rationale=items[i]["rationale"],
        )
        for i in range(len(weak_bullets))
    ]

    return RewriteSuggestionsRead(
        resume_id=resume.id,
        suggestions=suggestions,
        model=settings.ANTHROPIC_MODEL,
        generated_at=datetime.now(timezone.utc),
    )
