/** Suggested career / field-of-study options for the field-of-study (candidates)
 * and career-field (job descriptions) comboboxes. Free text is always allowed —
 * this is a suggestion list, not an enforced enum. */
export const CAREERS: string[] = [
  // Technology
  "Computer Science",
  "Information Technology (IT)",
  "Information Systems",
  "Software Engineering",
  "Computer Engineering",
  "Cybersecurity",
  "Information Security",
  "Network Engineering",
  "Network Administration",
  "Cloud Computing",
  "Cloud Engineering",
  "Data Science",
  "Data Analytics",
  "Artificial Intelligence",
  "Machine Learning",
  "Robotics",
  "Computer Vision",
  "Internet of Things (IoT)",
  "Web Development",
  "Mobile Application Development",
  "Database Administration",
  "Database Technology",
  "Systems Administration",
  "DevOps Engineering",
  "Blockchain Technology",
  "FinTech",
  "Game Development",
  "Game Design",
  "Computer Graphics",
  "UI/UX Design",
  "Human-Computer Interaction",
  "Digital Forensics",
  "Ethical Hacking",
  "IT Project Management",
  "IT Management",
  "Technology Management",
  "Telecommunications",
  "Information Architecture",
  "Software Development",
  "Embedded Systems",
  "Computer Networking",
  "Network Security",
  "Enterprise Architecture",
  "Business Intelligence",
  "Health Informatics",
  "Bioinformatics",

  // Business
  "Business Administration",
  "Business Management",
  "Accounting",
  "Finance",
  "Banking and Finance",
  "Economics",
  "Marketing",
  "Digital Marketing",
  "Human Resource Management",
  "Entrepreneurship",
  "International Business",
  "Management Information Systems",
  "Business Information Systems",
  "Operations Management",
  "Supply Chain Management",
  "Procurement and Logistics",
  "Project Management",
  "Business Analytics",
  "Financial Management",
  "Investment Management",
  "Insurance",
  "Actuarial Science",
  "Real Estate Management",
  "Hospitality Management",
  "Tourism Management",
  "Hotel Management",
  "Public Administration",
  "Public Management",
  "Office Administration",
  "Administrative Management",
  "Management Studies",
  "Strategic Management",
  "Corporate Governance",
  "Risk Management",
  "Sales Management",
  "Retail Management",
  "E-Commerce",
  "International Trade",
  "Transport Management",
  "Aviation Management",
  "Event Management",

  // Health & Medicine
  "General Nursing",
  "Registered Nursing",
  "Adult Nursing",
  "Pediatric Nursing",
  "Mental Health Nursing",
  "Community Nursing",
  "Public Health Nursing",
  "Midwifery",
  "Nurse Anesthesia",
  "Nurse Practitioner",
  "Critical Care Nursing",
  "Emergency Nursing",
  "Oncology Nursing",
  "Geriatric Nursing",
  "Neonatal Nursing",
  "Psychiatric Nursing",
  "Surgical Nursing",
  "Nursing Administration",
  "Nursing Education",
  "Medicine",
  "Surgery",
  "Dentistry",
  "Pharmacy",
  "Optometry",
  "Physiotherapy",
  "Occupational Therapy",
  "Radiography",
  "Medical Laboratory Science",
  "Biomedical Science",
  "Public Health",
  "Epidemiology",
  "Nutrition and Dietetics",
  "Health Administration",
  "Health Information Management",
  "Physician Assistant Studies",
  "Clinical Psychology",
  "Speech and Language Therapy",
  "Audiology",
  "Medical Imaging",
  "Emergency Medical Services",
  "Veterinary Medicine",

  // Engineering
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronics Engineering",
  "Chemical Engineering",
  "Petroleum Engineering",
  "Mining Engineering",
  "Geological Engineering",
  "Biomedical Engineering",
  "Environmental Engineering",
  "Agricultural Engineering",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Automotive Engineering",
  "Marine Engineering",
  "Telecommunications Engineering",
  "Industrial Engineering",
  "Manufacturing Engineering",
  "Structural Engineering",
  "Materials Engineering",
  "Mechatronics Engineering",
  "Robotics Engineering",
  "Renewable Energy Engineering",
  "Nuclear Engineering",
  "Systems Engineering",
  "Transportation Engineering",
  "Water Resources Engineering",
  "Architectural Engineering",

  // Design & Arts
  "Graphic Design",
  "Product Design",
  "Fashion Design",
  "Interior Design",
  "Industrial Design",
  "Architecture",
  "Fine Art",
  "Photography",
  "Animation",
  "Film Production",
  "Film Studies",
  "Video Production",
  "Multimedia Design",
  "Digital Media",
  "Music",
  "Theatre Arts",
  "Dance",
  "Illustration",
  "Creative Writing",
  "Art History",
  "Fashion Marketing",
  "Fashion Merchandising",
  "Culinary Arts",
  "Fashion Technology",

  // Education & Teaching
  "Education",
  "Early Childhood Education",
  "Primary Education",
  "Secondary Education",
  "Special Education",
  "Educational Leadership",
  "Curriculum and Instruction",
  "Adult Education",
  "TESOL / English Language Teaching",

  // Law
  "Law",
  "Criminal Justice",
  "Paralegal Studies",
  "International Law",
  "Human Rights Law",

  // Social Sciences & Humanities
  "Psychology",
  "Sociology",
  "Social Work",
  "Political Science",
  "International Relations",
  "Anthropology",
  "Philosophy",
  "History",
  "Linguistics",
  "Theology and Religious Studies",

  // Communications & Media
  "Journalism",
  "Mass Communication",
  "Public Relations",
  "Broadcasting",
  "Media Studies",

  // Agriculture & Environment
  "Agriculture",
  "Agribusiness",
  "Agricultural Science",
  "Forestry",
  "Fisheries and Aquaculture",
  "Environmental Science",
  "Environmental Management",
  "Sustainability Studies",
  "Horticulture",
  "Animal Science",

  // Natural Sciences & Mathematics
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Statistics",
  "Geography",
  "Geology",
  "Astronomy",

  // Sports & Recreation
  "Sports Science",
  "Physical Education",
  "Sports Management",
  "Recreation Management",

  // Other
  "Library and Information Science",
  "Urban and Regional Planning",
  "Social Entrepreneurship",
].sort((a, b) => a.localeCompare(b));
